Hw04 auth
4106677/nodejs-rest-api pull request #3
Opened 2023-02-16 19:37 UTC by 4106677

2023-02-17 18:50 UTC, Eastvarga requested changes
Є зауваження

2023-02-17 18:50 UTC, Eastvarga commented on middlewares/auth.js
> +    if (bearer !== 'Bearer') {
перевіряйте також токен, бо він може бути невизначенний

2023-02-17 18:50 UTC, Eastvarga commented on models/user.js
> +});
Схеми валідації та схеми моделей БД це різні поняття, не змішуйте їх.

2023-02-17 18:50 UTC, Eastvarga commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById));
auth чому тут немає мідлвару авторізації? Усі раути контактів повинні бути захищені

2023-02-17 18:50 UTC, Eastvarga commented on routes/api/contacts.js
>  router.delete('/:contactId', ctrlWrapper(ctrl.removeContact));
А для видалення теж авторізція чому не потрібна?

2023-02-19 13:57 UTC, NadyaHristuk approved these changes

2023-02-19 13:57 UTC, merged